#!/bin/bash

if [ -z "$@" ]
then
    echo NEW_NOTE
    echo TODAY
    echo VIMWIKI
    echo REVIEW
    cd ~/vimwiki/ && find -type f -name \*.md -not -path "./.archive/*" -not -path "./.trash/*" | cut -c3-
else
    if [[ "$@" == "TODAY" ]]; then
        coproc gvim "/home/jeroen/vimwiki/diary/`date +%Y-%m-%d`.md"
    elif [[ "$@" == "NEW_NOTE" ]]; then
        coproc gvim "+cd /home/jeroen/vimwiki" "+NewNote"
    elif [[ "$@" == "REVIEW" ]]; then
        coproc gvim "+cd /home/jeroen/vimwiki" "+Rg :REVIEW:" "/home/jeroen/vimwiki/diary/`date +%Y-%m-%d`.md"
    elif [[ "$@" == "VIMWIKI" ]]; then
        coproc gvim "+cd /home/jeroen/vimwiki" "/home/jeroen/vimwiki/index.md"
    else
        coproc gvim "/home/jeroen/vimwiki/$@"
    fi
fi
