#!/bin/bash

if [ -z "$@" ]
then
    hamster-cli list-activities
else
    coproc hamster-cli start $@ && sleep 0.1 && hamsterlist=$(hamster-cli list) && notify-send "hamster" "$hamsterlist" --icon=hamster-applet
fi
