#!/bin/bash

function run_rofi {
    rofi -dmenu -matching glob \
         -i \
         -p "dir: " \
         -mesg "      <b>Enter</b>: terminal | <b>Alt-r</b>: Ranger | <b>Alt-t</b>: Thunar | <b>Alt-o</b>: files" \
         -kb-custom-1 "Alt-r" \
         -kb-custom-2 "Alt-t" \
         -kb-custom-3 "Alt-o"
}

function run_rofi_files {
    rofi -dmenu -matching glob -i -p "file: "
}

function dir_drilldown_files {
    # cd to it so we only show the paths inside the dir, not the full paths
    if [ -x /opt/fd/fd ]; then
        cd "$1" && /opt/fd/fd -tf
    else
        cd "$1" && find -type f 2>&1 | grep -v "Permission denied"
    fi
}

function dir_drilldown {
    drill_result=$( dir_drilldown_files "$1" | run_rofi_files )
    drill_exit="$?"

    if [ "$drill_exit" -eq 0 ]
    then
        coproc xdg-open "$1/$drill_result"
    fi
}

result=$( ~/scripts/list-my-dirs.sh | run_rofi )
rofi_exit="$?"

case "$rofi_exit" in
    1)
        exit
        ;;
    10)
        coproc terminator -e "ranger '$result'"
        ;;
    11)
        coproc Thunar "$result"
        ;;
    12)
        dir_drilldown "$result"
        ;;
    0)
        cd "$result"
        coproc terminator
        ;;
esac
