#!/bin/bash

if [ $# -eq 0 ]
then
    show='combi'
else
    show=$1
fi

PATH=$PATH:`dirname $0` rofi \
    -show $show \
    -show-icons \
    -modi combi \
    -combi-modi media:rofi-mediaplayers,window,drun,vimwiki:rofi-vimwiki,vim:rofi-vim \
    -matching fuzzy \
    -hide-scrollbar true
    # -sidebar-mode \
    # -modi combi,vimwiki:rofi-vimwiki,ssh \
    # -modi combi,window,drun,ssh,vimwiki:rofi-vimwiki \
    # -combi-modi media:rofi-mediaplayers,window,drun,vim:rofi-vim,vimwiki:rofi-vimwiki \
